### training 

program: main.py

method: grid

metric:
  name: F1_test
  goal: maximize

parameters:
  channels:
    values: ["comp"]
  batch_size:
    values: [64]
  beta:
    values: [0.01, 0.1, 1, 10, 50]
  epochs:
    values: [100]
  learning_rate:
    values: [5e-4]
  ### VAE Loss
  epoch_resets:
    values: [25]
  num_resets:
    values: [1]
  ### VAE Model
  latent_dim:
    values: [2, 10, 50]
  model:
    values: ['cnn','mlp']
  ### normalization
  normalization:
    values: ['z-score', 'min-max']
  ### pre-processing
  level:
    values: [6, 7, 8] 
  wavelet:
    values: ['db4']