### training 

program: main.py

method: grid

metric:
  name: F1_test
  goal: maximize

parameters:
  channels:
    values: ["comp"]
  batch_size:
    values: [128]
  beta:
    values: [5,10,15,20,25]
  epochs:
    values: [100]
  learning_rate:
    values: [1e-5]
  ### VAE Loss
  epoch_resets:
    values: [25]
  num_resets:
    values: [1]
  ### VAE Model
  hidden_channels:
    values: [64]
  latent_dim:
    values: [2]
  model:
    values: ['cnn']
  ### normalization
  normalization:
    values: ['sum-z-score']
