### training 

program: main.py

method: grid

metric:
  name: F1_test
  goal: maximize

parameters:
  channels:
    values: ["comp"]
  batch_size:
    values: [64]
  beta:
    values: [0.01]
  epochs:
    values: [2]
  learning_rate:
    values: [1e-4]
  ### VAE Loss
  epoch_resets:
    values: [25]
  num_resets:
    values: [1]
  ### VAE Model
  latent_dim:
    values: [2]
  model:
    values: ['cnn']
  ### normalization
  normalization:
    values: ['min-max']
