### training 

program: main.py

method: grid

metric:
  name: F1_test
  goal: maximize

parameters:
  channels:
    values: ["comp"]
  batch_size:
    values: [128]
  beta:
    values: [0.01,0.1,1,10]
  epochs:
    values: [100]
  learning_rate:
    values: [1e-4]
  ### VAE Loss
  epoch_resets:
    values: [25]
  num_resets:
    values: [1]
  ### VAE Model
  latent_dim:
    values: [2]
  model:
    values: ['cnn']
  ### normalization
  normalization:
    values: ['db-z-score', 'z-score', 'min-max']
