### training 

program: main.py

method: grid

metric:
  name: F1_test
  goal: maximize

parameters:
  channels:
    values: ["comp"]
  batch_size:
    values: [64]
  beta:
    #values: [0.01,0.1,1,10]
    values: [20,30,40,50,60,70,80]
  epochs:
    values: [80]
  learning_rate:
    values: [1e-5]
  ### VAE Loss
  epoch_resets:
    values: [25]
  num_resets:
    values: [0]
  ### VAE Model
  hidden_channels:
    values: [64]
  latent_dim:
    values: [2]
  model:
    values: ['mlp']
  ### normalization
  normalization:
    values: ['min-max']
